// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jkgnqpsrnfzixoonkude.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImprZ25xcHNybmZ6aXhvb25rdWRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMzc1MDIsImV4cCI6MjA2NzgxMzUwMn0.59GpLCTrAvf2hqLT7xpY8M7-XQFEOaSM_RYtrqTTunA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});